{
    "openapi": "3.0.0",
    "info": {
        "title": "SKU Bindings API",
        "description": "The SKU Bindings API enables sellers to manage their SKUs offered across different VTEX marketplaces.\r\n\r\nIt allows sellers to send new suggestions to marketplaces, update SKU prices or inventory, and perform other operations, promoting accurate and flexible catalog management.\r\n\r\n## Index\r\n\r\n### SKU Bindings\r\n\r\n* `GET` [Get SKU bindings by SKU ID](https://developers.vtex.com/docs/api-reference/sku-bindings-api#get-/catalog/pvt/skusellers/-skuId-)\r\n* `GET` [Get SKU bindings information](https://developers.vtex.com/docs/api-reference/sku-bindings-api#get-/sku-binding/pvt/skuseller/admin)\r\n* `GET` [Get details of a seller's SKU](https://developers.vtex.com/docs/api-reference/sku-bindings-api#get-/sku-binding/pvt/skuseller/-sellerId-/-sellerSkuId-)\r\n* `PUT` [Bind a seller's SKU to another SKU](https://developers.vtex.com/docs/api-reference/sku-bindings-api#put-/sku-binding/pvt/skuseller/-sellerId-/-sellerSkuId-)\r\n* `GET` [Get all SKU bindings by seller ID](https://developers.vtex.com/docs/api-reference/sku-bindings-api#get-/sku-binding/pvt/skuseller/list/bysellerId/-sellerId-)\r\n* `GET` [Get paged SKU bindings by seller ID](https://developers.vtex.com/docs/api-reference/sku-bindings-api#get-/sku-binding/pvt/skuseller/paged/sellerid/-sellerId-)\r\n* `POST` [Change notification with SKU ID](https://developers.vtex.com/docs/api-reference/sku-bindings-api#post-/sku-binding/pvt/skuseller/changenotification/-skuId-)\r\n* `POST` [Change notification with seller ID and seller SKU ID](https://developers.vtex.com/docs/api-reference/sku-bindings-api#post-/sku-binding/pvt/skuseller/changenotification/-sellerId-/-sellerSkuId-)\r\n* `POST` [Insert SKU binding](https://developers.vtex.com/docs/api-reference/sku-bindings-api#post-/sku-binding/pvt/skuseller/insertion)\r\n* `POST` [Activate SKU binding](https://developers.vtex.com/docs/api-reference/sku-bindings-api#post-/sku-binding/pvt/skuseller/activate/-sellerId-/-skuSellerId-)\r\n* `POST` [Deactivate SKU binding](https://developers.vtex.com/docs/api-reference/sku-bindings-api#post-/sku-binding/pvt/skuseller/inactivate/-sellerId-/-skuSellerId-)\r\n* `POST` [Remove a seller's SKU binding](https://developers.vtex.com/docs/api-reference/sku-bindings-api#post-/sku-binding/pvt/skuseller/remove/-sellerId-/-sellerSkuId-)\r\n\r\n## Common parameters\r\n\r\n| **Parameter name** | **Description** | **Type** |\r\n| :---: | :--- | :--- |\r\n| `{{accountName}}` | Name of the VTEX account. Used as part of the URL. | Server variable. |\r\n| `{{environment}}` | Environment to use. Used as part of the URL. The default value is `vtexcommercestable`. | Server variable. |\r\n| `X-VTEX-API-AppKey` | Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys). | Authentication header. Must be used together with `X-VTEX-API-AppToken`. Not necessary when using `VtexIdclientAutCookie`. |\r\n| `X-VTEX-API-AppToken` | Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys). | Authentication header. Must be used together with X-VTEX-API-AppKey. Not necessary when using `VtexIdclientAutCookie`. |\r\n| `VtexIdclientAutCookie` | [User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours. | Authentication header. Not necessary when using `X-VTEX-API-AppKey` and `X-VTEX-API-AppToken`. |",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br/api",
            "description": "VTEX server URL.",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL.",
                    "default": "apiexamples"
                },
                 "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "enum": [
                        "vtexcommercestable"
                    ],
                    "default": "vtexcommercestable"
                }
            }
        }
    ],
    "paths": {
        "/catalog/pvt/skusellers/{skuId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get SKU bindings by SKU ID",
                "description": "Retrieves SKU bindings details searching by SKU ID.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "GetbySkuId",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "SKU's unique identifier in the marketplace.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "description": "Array containing objects with information about each SKU Binding.",
                                    "items": {
                                        "type": "object",
                                        "description": "Object with information about an SKU Binding.",
                                        "properties": {
                                            "Id": {
                                                "type": "integer",
                                                "description": "SKU Binding ID."
                                            },
                                            "SellerId": {
                                                "type": "string",
                                                "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID."
                                            },
                                            "StockKeepingUnitId": {
                                                "type": "integer",
                                                "description": "SKU ID in the VTEX marketplace."
                                            },
                                            "SellerSkuId": {
                                                "type": "string",
                                                "description": "SKU seller ID."
                                            },
                                            "IsActive": {
                                                "type": "boolean",
                                                "description": "Defines if the SKU binding is active."
                                            },
                                            "LastUpdateDate": {
                                                "type": "string",
                                                "description": "Date when the SKU binding was updated for the last time, in UTC format."
                                            },
                                            "SalesPolicy": {
                                                "type": "integer",
                                                "description": "Sales policy ID."
                                            }
                                        }
                                    }
                                },
                                "example": [
                                    {
                                        "Id": 48,
                                        "SellerId": "cosmetics1",
                                        "StockKeepingUnitId": 1,
                                        "SellerSkuId": "42",
                                        "IsActive": true,
                                        "LastUpdateDate": "2025-10-21T19:13:00.657",
                                        "SalesPolicy": 0
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/admin": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get SKU bindings information",
                "description": "Retrieves SKU bindings administrative information using optional query params `sellerId`, `skuId`, `sellerSkuId` and `IsActive` to filter results and `size` to restrict the amount of results.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/admin`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "Getpagedadmin",
                "parameters": [
                    {
                        "name": "sellerId",
                        "in": "query",
                        "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID.",
                        "required": false,
                        "style": "form",
                        "schema": {
                            "type": "string",
                            "example": "vtxkfj7352"
                        }
                    },
                    {
                        "name": "skuId",
                        "in": "query",
                        "description": "SKU's unique identifier in the marketplace.",
                        "required": false,
                        "style": "form",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "query",
                        "description": "SKU ID in the seller's store.",
                        "required": false,
                        "style": "form",
                        "schema": {
                            "type": "string",
                            "example": "71"
                        }
                    },
                    {
                        "name": "isActive",
                        "in": "query",
                        "description": "Defines if the SKU binding is active.",
                        "required": false,
                        "style": "form",
                        "schema": {
                            "type": "boolean",
                            "example": true
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "Amount of results.",
                        "required": false,
                        "style": "form",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "description": "SKU bindings information regarding a given seller ID.",
                                        "properties": {
                                            "IsPersisted": {
                                                "type": "boolean",
                                                "description": "Defines if the seller is persisted."
                                            },
                                            "IsRemoved": {
                                                "type": "boolean",
                                                "description": "Defines if the seller is removed."
                                            },
                                            "SkuSellerId": {
                                                "type": "integer",
                                                "description": "SKU Binding ID."
                                            },
                                            "UpdateDate": {
                                                "type": "string",
                                                "description": "Date when the SKU binding was updated for the last time, in UTC format."
                                            },
                                            "RequestedUpdateDate": {
                                                "type": "string",
                                                "description": "Date when an SKU binding update was requested for the last time, in UTC format.",
                                                "nullable": true
                                            },
                                            "SellerStockKeepingUnitId": {
                                                "type": "string",
                                                "description": "SKU ID in the seller's store."
                                            },
                                            "SellerId": {
                                                "type": "string",
                                                "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID."
                                            },
                                            "StockKeepingUnitId": {
                                                "type": "integer",
                                                "description": "SKU ID in the VTEX marketplace."
                                            },
                                            "IsActive": {
                                                "type": "boolean",
                                                "description": "Defines if the SKU binding is active."
                                            }
                                        }
                                    }
                                },
                                "example": [
                                    {
                                        "IsPersisted": true,
                                        "IsRemoved": false,
                                        "SkuSellerId": 102,
                                        "UpdateDate": "2025-04-12T20:06:59.413Z",
                                        "RequestedUpdateDate": null,
                                        "SellerStockKeepingUnitId": "71",
                                        "SellerId": "fashionstore",
                                        "StockKeepingUnitId": 25,
                                        "IsActive": true
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/{sellerId}/{sellerSkuId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get details of a seller's SKU",
                "description": "Retrieves a seller SKU details, given a seller ID and the SKU ID in the seller's store.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/{sellerId}/{sellerSkuId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "GetSKUseller",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "SKU ID in the seller's store.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "required": [
                                        "IsPersisted",
                                        "IsRemoved",
                                        "SkuSellerId",
                                        "SellerId",
                                        "StockKeepingUnitId",
                                        "SellerStockKeepingUnitId",
                                        "IsActive",
                                        "UpdateDate",
                                        "RequestedUpdateDate"
                                    ],
                                    "properties": {
                                        "IsPersisted": {
                                            "type": "boolean",
                                            "description": "Defines if the seller is persisted."
                                        },
                                        "IsRemoved": {
                                            "type": "boolean",
                                            "description": "Defines if the seller is removed."
                                        },
                                        "SkuSellerId": {
                                            "type": "integer",
                                            "description": "SKU ID in the seller's store."
                                        },
                                        "UpdateDate": {
                                            "type": "string",
                                            "description": "Date when the SKU binding was updated for the last time, in UTC format."
                                        },
                                        "RequestedUpdateDate": {
                                            "type": "string",
                                            "description": "Date when an SKU binding update was requested for the last time, in UTC format.",
                                            "nullable": true
                                        },
                                        "SellerStockKeepingUnitId": {
                                            "type": "string",
                                            "description": "SKU seller ID."
                                        },
                                        "SellerId": {
                                            "type": "string",
                                            "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID."
                                        },
                                        "StockKeepingUnitId": {
                                            "type": "integer",
                                            "description": "SKU ID in the VTEX marketplace."
                                        },
                                        "IsActive": {
                                            "type": "boolean",
                                            "description": "Defines if the SKU binding is active."
                                        }
                                    }
                                },
                                "example": {
                                    "IsPersisted": true,
                                    "IsRemoved": false,
                                    "SkuSellerId": 799,
                                    "UpdateDate": "2025-10-11T04:52:42.1",
                                    "RequestedUpdateDate": null,
                                    "SellerStockKeepingUnitId": "502",
                                    "SellerId": "fashionstore",
                                    "StockKeepingUnitId": 50,
                                    "IsActive": true
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Bind a seller's SKU to another SKU",
                "description": "Associates a seller's SKU to another marketplace SKU.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/{sellerId}/{sellerSkuId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "Bindtoanothersku",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "SKU ID in the seller's store.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "StockKeepingUnitId"
                                ],
                                "type": "object",
                                "properties": {
                                    "StockKeepingUnitId": {
                                        "type": "integer",
                                        "description": "SKU ID in the marketplace.",
                                        "example": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/list/bysellerId/{sellerId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get all SKU bindings by seller ID",
                "description": "Retrieves a list of SKU bindings given a specific seller ID.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/list/bysellerId/{sellerId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "GetallbySellerId",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "description": "Seller's SKU bindings information.",
                                        "properties": {
                                            "SellerStockKeepingUnitId": {
                                                "type": "string",
                                                "description": "SKU ID in the seller's store."
                                            },
                                            "FreightCommissionPercentage": {
                                                "type": "number",
                                                "description": "The percentage that must be filled in as agreed between the marketplace and the seller.",
                                                "nullable": true
                                            },
                                            "ProductCommissionPercentage": {
                                                "type": "number",
                                                "description": "The percentage that must be filled in as agreed between the marketplace and the seller. If there is no such commission, please fill in the field with the value: `0.00`.",
                                                "nullable": true
                                            },
                                            "SellerId": {
                                                "type": "string",
                                                "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID."
                                            },
                                            "StockKeepingUnitId": {
                                                "type": "integer",
                                                "description": "SKU ID in the marketplace."
                                            },
                                            "IsActive": {
                                                "type": "boolean",
                                                "description": "Defines if the SKU binding is active."
                                            }
                                        }
                                    }
                                },
                                "example": [
                                    {
                                        "SellerStockKeepingUnitId": "24",
                                        "FreightCommissionPercentage": null,
                                        "ProductCommissionPercentage": null,
                                        "SellerId": "fashionstore",
                                        "StockKeepingUnitId": 121,
                                        "IsActive": true
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/paged/sellerid/{sellerId}": {
            "get": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Get paged SKU bindings by seller ID",
                "description": "Retrieves a paged list of SKU bindings given a specific seller ID.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/paged/sellerid/{sellerId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "GetpagedbySellerId",
                "parameters": [
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page number.",
                        "required": true,
                        "style": "form",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "Amount of results per page.",
                        "required": true,
                        "style": "form",
                        "schema": {
                            "type": "string",
                            "example": "2"
                        }
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "description": "SKU binding information regarding a given seller ID.",
                                        "properties": {
                                            "SellerId": {
                                                "type": "string",
                                                "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the Admin to get the correct ID."
                                            },
                                            "StockKeepingUnitId": {
                                                "type": "integer",
                                                "description": "SKU ID in the marketplace."
                                            },
                                            "SellerStockKeepingUnitId": {
                                                "type": "string",
                                                "description": "SKU ID in the seller's store."
                                            },
                                            "IsActive": {
                                                "type": "boolean",
                                                "description": "Defines if the SKU binding is active."
                                            },
                                            "FreightCommissionPercentage": {
                                                "type": "number",
                                                "description": "The percentage that must be filled in as agreed between the marketplace and the seller.",
                                                "nullable": true
                                            },
                                            "ProductCommissionPercentage": {
                                                "type": "number",
                                                "description": "The percentage that must be filled in as agreed between the marketplace and the seller. If there is no such commission, please fill in the field with the value: `0.00`.",
                                                "nullable": true
                                            }
                                        }
                                    }
                                },
                                "example": [
                                    {
                                        "SellerId": "101",
                                        "StockKeepingUnitId": 121,
                                        "SellerStockKeepingUnitId": "24",
                                        "IsActive": true,
                                        "FreightCommissionPercentage": null,
                                        "ProductCommissionPercentage": null
                                    },
                                    {
                                        "SellerId": "fashionstore",
                                        "StockKeepingUnitId": 14,
                                        "SellerStockKeepingUnitId": "60",
                                        "IsActive": true,
                                        "FreightCommissionPercentage": null,
                                        "ProductCommissionPercentage": null
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/changenotification/{skuId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Change notification with SKU ID",
                "description": "Sends a seller notification to the VTEX marketplace about a SKU suggestion using the SKU ID. It can be either a new suggestion or an update to an existing one. For example, a seller SKU previously approved by the marketplace may have had price or inventory changes.\r\n\r\nThis request does not require a request body.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/changenotification/{skuId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "ChangeNotification",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "A string that identifies the SKU in the marketplace. This is the ID that the marketplace will use to look for the SKU whose change the seller wants to inform. If the marketplace finds this ID, it responds with status code `200`. Otherwise, it responds with status code `404`.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "10"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "429": {
                        "description": "Too many requests"
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/changenotification/{sellerId}/{sellerSkuId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Change notification with seller ID and seller SKU ID",
                "description": "Sends a seller notification to the VTEX marketplace about a SKU suggestion, which can be either a new suggestion or an update. For example, a seller SKU previously approved by the marketplace may have had price or inventory changes.\r\n\r\nThe main information sent by the seller is its identification (`sellerId`) and the SKU binding code (`sellerSkuId`), both passed as path parameters. This request doesn't require a request body.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/changenotification/{sellerId}/{sellerSkuId}`.\r\n\r\n## Example\r\n\r\nLet's say your seller has the ID `123` in the marketplace, and you want to inform the marketplace that there has been a change to the SKU with ID `700`.\r\n\r\nIn this case, you would replace the `sellerId` parameter with the value `123`, and the `sellerSkuId` parameter with the value `700`. The URL would be the following:\r\n\r\n```\r\nhttps:\/\/accountName.vtexcommercestable.com.br\/api\/sku-binding\/pvt\/skuseller\/changenotification\/123\/700\r\n```\r\n\r\n## Response codes\r\n\r\nThe following response codes are possible:\r\n* 200: The SKU whose ID was informed in the URL already exists in the marketplace and was found. The marketplace can now proceed with a fulfillment simulation in order to get updated information about this SKU's inventory and price.\r\n* 403: Failure in the authentication.\r\n* 404: The SKU was not found in the marketplace. The body of the response, in this case, should follow this format: \"Seller StockKeepingUnit `{{skuId}}` not found for this seller id `{{sellerId}}`. This means that the seller can now proceed with sending an offer to the marketplace in order to suggest that this SKU is sold there.\r\n* 429: Failure due to too many requests.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "ID of the binding of the seller with the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "429": {
                        "description": "Too many requests"
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/insertion": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Insert SKU binding",
                "description": "Creates an SKU binding, associating a seller's SKU with a marketplace's SKU.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/insertion`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "InsertSKUBinding",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "StockKeepingUnitId",
                                    "IsActive",
                                    "SellerId",
                                    "SellerStockKeepingUnitId"
                                ],
                                "type": "object",
                                "properties": {
                                    "StockKeepingUnitId": {
                                        "type": "integer",
                                        "description": "SKU ID in the marketplace.",
                                        "example": 1
                                    },
                                    "IsActive": {
                                        "type": "boolean",
                                        "description": "Defines whether the SKU binding is active (`true`) or inactive (`false`).",
                                        "example": true
                                    },
                                    "SellerId": {
                                        "type": "string",
                                        "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the VTEX Admin to get the correct ID.",
                                        "example": "fashionstore"
                                    },
                                    "SellerStockKeepingUnitId": {
                                        "type": "string",
                                        "description": "SKU seller ID.",
                                        "example": "71"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "409": {
                        "description": "Conflict"
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/activate/{sellerId}/{skuSellerId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Activate SKU binding",
                "description": "Changes the status of an SKU binding to active, setting `isActive` to `true`.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/activate/{sellerId}/{skuSellerId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "ActivateSKUBinding",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    },
                    {
                        "name": "skuSellerId",
                        "in": "path",
                        "description": "SKU ID in the seller's store.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "71"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/inactivate/{sellerId}/{skuSellerId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Deactivate SKU binding",
                "description": "Changes the status of an SKU binding to inactive, setting `isActive` to `false`.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/inactivate/{sellerId}/{skuSellerId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "DeactivateSKUBinding",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    },
                    {
                        "name": "skuSellerId",
                        "in": "path",
                        "description": "SKU ID in the seller's store.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "71"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/sku-binding/pvt/skuseller/remove/{sellerId}/{sellerSkuId}": {
            "post": {
                "tags": [
                    "SKU Bindings"
                ],
                "summary": "Remove a seller's SKU binding",
                "description": "Removes a seller's SKU binding, given the seller ID and the SKU ID in the seller's store.\r\n\r\n > â„¹ This path is an updated version of `/api/catalog_system/pvt/skuseller/remove/{sellerId}/{sellerSkuId}`.\r\n\r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
                "operationId": "DeleteSKUsellerassociation",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/SellerId"
                    },
                    {
                        "name": "sellerSkuId",
                        "in": "path",
                        "description": "SKU ID in the seller's store.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "71"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "security": [
        {
            "appKey": [],
            "appToken": []
        },
        {
            "VtexIdclientAutCookie": []
        }
    ],
    "components": {
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey",
                "description": "Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken",
                "description": "Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
            },
            "VtexIdclientAutCookie": {
                "type": "apiKey",
                "in": "header",
                "name": "VtexIdclientAutCookie",
                "description": "[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours."
            }
        },
        "parameters": {
            "Content-Type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Type of the content being sent.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            },
            "Accept": {
                "name": "Accept",
                "in": "header",
                "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            },
            "SellerId": {
                "name": "sellerId",
                "in": "path",
                "description": "ID that identifies the seller in the marketplace. It can be the same as the seller name or a unique number. Check the **Sellers management** section in the VTEX Admin to get the correct ID.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "fashionstore"
                }
            }
        }
    },
    "tags": [
        {
            "name": "SKU Bindings"
        }
    ]
}