{
    "openapi": "3.0.0",
    "info": {
        "title": "Pick and Pack Order changes API",
        "description": "The Pick and Pack Order changes API manages order modifications in a Pick and Pack order. This API supports actions like updating deadlines, adding items, modifying quantities, rejecting or replacing items, and updating item details.\r\n\r\n>ℹ️ This API is currently in beta and subject to changes. Use it with caution in production environments.\r\n\r\n## Order changes\r\n\r\n- `PUT` [Update order deadline](https:\/\/developers.vtex.com\/docs\/api-reference\/pick-and-pack-order-changes-api#put-\/orders\/-orderId-\/deadline)\r\n\r\n## Bin locations\r\n\r\n- [`GET` Get bin location](https:\/\/developers.vtex.com\/docs\/api-reference\/pick-and-pack-order-changes-api#get-\/-skuId-\/warehouses\/-warehouseId-)\r\n- [`POST` Create bin location](https:\/\/developers.vtex.com\/docs\/api-reference\/pick-and-pack-order-changes-api#post-\/-skuId-\/warehouses\/-warehouseId-)\r\n- [`PUT` Update bin location](https:\/\/developers.vtex.com\/docs\/api-reference\/pick-and-pack-order-changes-api#put-\/-skuId-\/warehouses\/-warehouseId-)\r\n- [`DELETE` Delete bin location](https:\/\/developers.vtex.com\/docs\/api-reference\/pick-and-pack-order-changes-api#delete-\/-skuId-\/warehouses\/-warehouseId-)\r\n\r\n## Common parameters\r\n\r\n| Parameter name | Description | Type |\r\n| --- | --- | --- |\r\n| `{{accountName}}` | Name of the VTEX account. Used as part of the URL. | Server variable. |\r\n| `{{environment}}` | Environment to use. The default value is `vtexcommercestable`. Used in the URL. | Server variable. |\r\n| `X-VTEX-API-AppKey` | Unique identifier of the API key. Must be used together with `X-VTEX-API-AppToken`. | Authentication header |\r\n| `X-VTEX-API-AppToken` | Secret token of the API key. Must be used together with `X-VTEX-API-AppKey`. | Authentication header |\r\n| `VtexIdclientAutCookie` | User token valid for 24 hours. Alternative to `appKey` + `appToken`. | Authentication header |",

        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br/vtex_pickandpack",
            "description": "VTEX server URL.",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL.",
                    "default": "apiexamples"
                },
                "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "enum": ["vtexcommercestable"],
                    "default": "vtexcommercestable"
                }
            }
        },
        {
            "url": "https://{accountName}.myvtex.com/pickpack/bin-location",
            "description": "VTEX server URL.",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL.",
                    "default": "apiexamples"
                }
            }
        }
    ],
    "paths": {
        "/orders/{orderId}/deadline": {
            "put": {
                "summary": "Update order deadline",
                "description": "Updates the deadline for an order. The `min` and `max` fields specify the deadline window, while the description provides additional information.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/orderId"
                    },
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    }
                ],
                "tags": [
                    "Order changes"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateDeadlineRequest"
                            },
                            "example": {
                                "description": "Extend deadline due to delayed shipment",
                                "max": "2024-12-24T23:03:02Z",
                                "min": "2024-12-23T23:03:02Z"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UpdateDeadlineResponse"
                                },
                                "example": {
                                    "order": {
                                        "currentDeadline": {
                                            "max": "2024-12-24T23:03:02Z",
                                            "min": "2024-12-23T23:03:02Z"
                                        },
                                        "deadlineChanges": [
                                            {
                                                "current": true,
                                                "description": "Extend deadline due to delayed shipment",
                                                "handled": true,
                                                "max": "2024-12-24T23:03:02.000Z",
                                                "min": "2024-12-23T23:03:02.000Z",
                                                "oldDates": {
                                                    "max": "2024-12-04T17:20:48.088Z",
                                                    "min": "2024-12-04T17:20:48.088Z"
                                                },
                                                "updatedAt": "2024-12-03T17:35:59.786Z"
                                            }
                                        ],
                                        "orderId": "1481050515517-01"
                                    },
                                    "success": true
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "description": "Request error object with error information.",
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "description": "Error code.",
                                                    "type": "string"
                                                },
                                                "message": {
                                                    "description": "Error message.",
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "success": {
                                            "description": "Condition if the request was successful.",
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "example": {
                                    "error": {
                                        "code": "400",
                                        "message": "New dates must be greater than the current dates"
                                    },
                                    "success": false
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "description": "Authentication failed due to missing, invalid, or expired credentials. Ensure the `X-VTEX-API-AppKey` and `X-VTEX-API-AppToken` headers include valid values.",
                                            "type": "string"
                                        }
                                    }
                                },
                                "example": {
                                    "message": "Unauthorized"
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/{skuId}/warehouses/{warehouseId}": {
            "get": {
                "summary": "Get bin location",
                "security": [
                    {
                        "VtexIdclientAutCookie": []
                    }
                ],
                "description": "Retrieves the bin location for a specific SKU in a warehouse. The bin location is a specific, designated storage location within a warehouse. This location isn't necessarily a physical container. Each bin is typically assigned a unique identifier or code, facilitating precise tracking and retrieval of items within the warehouse.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "Unique identifier of the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "name": "warehouseId",
                        "in": "path",
                        "description": "Unique identifier of the warehouse.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "10"
                        }
                    }
                ],
                "tags": [
                    "Bin locations"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "location": {
                                            "type": "string",
                                            "description": "The bin location within the warehouse."
                                        },
                                        "hostname": {
                                            "type": "string",
                                            "description": "The account name managing the bin location."
                                        },
                                        "warehouseId": {
                                            "type": "string",
                                            "description": "The identifier of the warehouse."
                                        },
                                        "skuId": {
                                            "type": "string",
                                            "description": "The identifier of the SKU."
                                        }
                                    }
                                },
                                "example": {
                                    "location": "My location 14",
                                    "hostname": "lastmile",
                                    "warehouseId": "10",
                                    "skuId": "1"
                                }
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "https://{accountName}.myvtex.com/pickpack/bin-location",
                        "description": "VTEX server URL.",
                        "variables": {
                            "accountName": {
                                "description": "Name of the VTEX account. Used as part of the URL.",
                                "default": "apiexamples"
                            }
                        }
                    }
                ]
            },
            "post": {
                "summary": "Create bin location",
                "security": [
                    {
                        "VtexIdclientAutCookie": []
                    }
                ],
                "description": "Creates a new bin location by warehouse ID and SKU ID. The bin location is a specific, designated storage location within a warehouse. This location isn't necessarily a physical container. Each bin is typically assigned a unique identifier or code, facilitating precise tracking and retrieval of items within the warehouse.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "tags": [
                    "Bin locations"
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "Unique identifier of the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "name": "warehouseId",
                        "in": "path",
                        "description": "Unique identifier of the warehouse.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "10"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "location": {
                                        "type": "string",
                                        "description": "The bin location within the warehouse."
                                    }
                                },
                                "required": ["location"]
                            },
                            "example": {
                                "location": "My location 14"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "location": {
                                            "type": "string",
                                            "description": "The bin location within the warehouse."
                                        },
                                        "hostname": {
                                            "type": "string",
                                            "description": "The account name managing the bin location."
                                        },
                                        "warehouseId": {
                                            "type": "string",
                                            "description": "The identifier of the warehouse."
                                        },
                                        "skuId": {
                                            "type": "string",
                                            "description": "The identifier of the SKU."
                                        }
                                    }
                                },
                                "example": {
                                    "location": "My location 14",
                                    "hostname": "lastmile",
                                    "warehouseId": "10",
                                    "skuId": "1"
                                }
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "https://{accountName}.myvtex.com/pickpack/bin-location",
                        "description": "VTEX server URL.",
                        "variables": {
                            "accountName": {
                                "description": "Name of the VTEX account. Used as part of the URL.",
                                "default": "apiexamples"
                            }
                        }
                    }
                ]
            },
            "put": {
                "summary": "Update bin location",
                "security": [
                    {
                        "VtexIdclientAutCookie": []
                    }
                ],
                "description": "Updates the bin location by warehouse ID and SKU ID. The bin location is a specific, designated storage location within a warehouse. This location isn't necessarily a physical container. Each bin is typically assigned a unique identifier or code, facilitating precise tracking and retrieval of items within the warehouse.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "tags": [
                    "Bin locations"
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "Unique identifier of the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "name": "warehouseId",
                        "in": "path",
                        "description": "Unique identifier of the warehouse.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "10"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "location": {
                                        "type": "string",
                                        "description": "The bin location within the warehouse."
                                    }
                                },
                                "required": ["location"]
                            },
                            "example": {
                                "location": "My location 14"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "location": {
                                            "type": "string",
                                            "description": "The bin location within the warehouse."
                                        },
                                        "hostname": {
                                            "type": "string",
                                            "description": "The account name managing the bin location."
                                        },
                                        "warehouseId": {
                                            "type": "string",
                                            "description": "The identifier of the warehouse."
                                        },
                                        "skuId": {
                                            "type": "string",
                                            "description": "The identifier of the SKU."
                                        }
                                    }
                                },
                                "example": {
                                    "location": "My location 14",
                                    "hostname": "lastmile",
                                    "warehouseId": "10",
                                    "skuId": "1"
                                }
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "https://{accountName}.myvtex.com/pickpack/bin-location",
                        "description": "VTEX server URL.",
                        "variables": {
                            "accountName": {
                                "description": "Name of the VTEX account. Used as part of the URL.",
                                "default": "apiexamples"
                            }
                        }
                    }
                ]
            },
            "delete": {
                "summary": "Delete bin location",
                "security": [
                    {
                        "VtexIdclientAutCookie": []
                    }
                ],
                "description": "Deletes a specific bin location by warehouse ID and SKU ID. The bin location is a specific, designated storage location within a warehouse. This location isn't necessarily a physical container. Each bin is typically assigned a unique identifier or code, facilitating precise tracking and retrieval of items within the warehouse.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "tags": [
                    "Bin locations"
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "Unique identifier of the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    },
                    {
                        "name": "warehouseId",
                        "in": "path",
                        "description": "Unique identifier of the warehouse.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "10"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "description": "Empty array.",
                                    "items": {
                                        "type": "object",
                                        "description": "Empty response item."
                                    }
                                },
                                "example": []
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "https://{accountName}.myvtex.com/pickpack/bin-location",
                        "description": "VTEX server URL.",
                        "variables": {
                            "accountName": {
                                "description": "Name of the VTEX account. Used as part of the URL.",
                                "default": "apiexamples"
                            }
                        }
                    }
                ]
            }
        },
        "/{skuId}/warehouses":{
            "get": {
                "summary": "List bin locations",
                "security": [
                    {
                        "VtexIdclientAutCookie": []
                    }
                ],
                "description": "Retrieves a list of warehouses associated with a specific SKU ID. The bin location is a specific, designated storage location within a warehouse. This location isn't necessarily a physical container. Each bin is typically assigned a unique identifier or code, facilitating precise tracking and retrieval of items within the warehouse.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "tags": [
                    "Bin locations"
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "Unique identifier of the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "description": "bin location",
                                        "type": "object",
                                        "properties": {
                                            "location": {
                                                "type": "string",
                                                "description": "The bin location within the warehouse."
                                            },
                                            "hostname": {
                                                "type": "string",
                                                "description": "The account name managing the bin location."
                                            },
                                            "warehouseId": {
                                                "type": "string",
                                                "description": "The identifier of the warehouse."
                                            },
                                            "skuId": {
                                                "type": "string",
                                                "description": "The identifier of the SKU."
                                            }
                                        }
                                    }
                                },
                                "example": [
                                    {
                                        "location": "My location 14 edited",
                                        "hostname": "lastmile",
                                        "warehouseId": "14",
                                        "skuId": "2"
                                    },
                                    {
                                        "location": "My location 15 edited",
                                        "hostname": "lastmile",
                                        "warehouseId": "15",
                                        "skuId": "1"
                                    },
                                    {
                                        "location": "My location 4 edited",
                                        "hostname": "lastmile",
                                        "warehouseId": "10",
                                        "skuId": "7"
                                    }
                                ]
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "https://{accountName}.myvtex.com/pickpack/warehouses",
                        "description": "VTEX server URL.",
                        "variables": {
                            "accountName": {
                                "description": "Name of the VTEX account. Used as part of the URL.",
                                "default": "apiexamples"
                            }
                        }
                    }
                ]
            },
            "delete":{
                "summary": "Delete all bin locations",
                "security": [
                    {
                        "VtexIdclientAutCookie": []
                    }
                ],
                "description": "Deletes all bin locations for a specific SKU ID. The bin location is a specific, designated storage location within a warehouse. This location isn't necessarily a physical container. Each bin is typically assigned a unique identifier or code, facilitating precise tracking and retrieval of items within the warehouse.\r\n\r\n>ℹ️ This endpoint is currently in beta and subject to changes. Use with caution in production environments.\r\n\r\n## Permissions\r\n\r\nAny user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:\r\n\r\n| **Product** | **Category** | **Resource** |\r\n| --------------- | ----------------- | ----------------- |\r\n| OMS | OMS access | **View order** |\r\n| OMS | OMS access | **Only show orders created by the user (via call center)** |\r\n| Catalog | Telesales | **Assisted Sales** |\r\n\r\nThere are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).\r\n\r\n>\u2757 To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.",
                "tags": [
                    "Bin locations"
                ],
                "parameters": [
                    {
                        "$ref": "#/components/parameters/Accept"
                    },
                    {
                        "$ref": "#/components/parameters/Content-Type"
                    },
                    {
                        "name": "skuId",
                        "in": "path",
                        "description": "Unique identifier of the SKU.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "description": "Empty array.",
                                    "items": {
                                        "type": "object",
                                        "description": "Empty response item."
                                    }
                                },
                                "example": []
                            }
                        }
                    }
                }
            }
        }
    },
    "security": [
        {
            "appKey": [],
            "appToken": []
        },
        {
            "VtexIdclientAutCookie": []
        }
    ],
    "components": {
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey",
                "description": "Unique identifier of the [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys)."
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken",
                "description": "Secret token of the [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys)."
            },
            "VtexIdclientAutCookie": {
                "type": "apiKey",
                "in": "header",
                "name": "VtexIdclientAutCookie",
                "description": "[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours."
            }
        },
        "schemas": {
            "UpdateDeadlineRequest": {
                "required": ["description", "max", "min"],
                "type": "object",
                "description": "Contains deadline information.",
                "properties": {
                    "description": {
                        "type": "string",
                        "description": "Reason or purpose of the deadline change."
                    },
                    "max": {
                        "type": "string",
                        "description": "Latest deadline date in ISO 8601 format."
                    },
                    "min": {
                        "type": "string",
                        "description": "Earliest deadline date in ISO 8601 format."
                    }
                },
                "example": {
                    "description": "Extend deadline due to delayed shipment",
                    "max": "2024-12-24T23:03:02Z",
                    "min": "2024-12-23T23:03:02Z"
                }
            },
            "UpdateDeadlineResponse": {
                "type": "object",
                "description": "Update deadline response.",
                "properties": {
                    "order": {
                        "description": "Object with current deadline information.",
                        "type": "object",
                        "properties": {
                            "currentDeadline": {
                                "description": "Current deadline information.",
                                "type": "object",
                                "properties": {
                                    "max": {
                                        "description": "Latest deadline date in ISO 8601 format.",
                                        "type": "string"
                                    },
                                    "min": {
                                        "description": "Earliest deadline date in ISO 8601 format.",
                                        "type": "string"
                                    }
                                }
                            },
                            "deadlineChanges": {
                                "description": "Object containg information of the deadline changes.",
                                "type": "array",
                                "items": {
                                    "description": "Deadline change.",
                                    "type": "object",
                                    "properties": {
                                        "current": {
                                            "description": "If the deadline changes were update.",
                                            "type": "boolean"
                                        },
                                        "description": {
                                            "description": "Reason or purpose for the update.",
                                            "type": "string"
                                        },
                                        "handled": {
                                            "description": "If the deadline changes were handled by the picker.",
                                            "type": "boolean"
                                        },
                                        "max": {
                                            "description": "Latest deadline date in ISO 8601 format.",
                                            "type": "string"
                                        },
                                        "min": {
                                            "description": "Earliest deadline date in ISO 8601 format.",
                                            "type": "string"
                                        },
                                        "oldDates": {
                                            "description": "Object containg previous deadline information.",
                                            "type": "object",
                                            "properties": {
                                                "max": {
                                                    "description": "Latest deadline date in ISO 8601 format.",
                                                    "type": "string"
                                                },
                                                "min": {
                                                    "description": "Earliest deadline date in ISO 8601 format.",
                                                    "type": "string"
                                                }
                                            }
                                        },
                                        "updatedAt": {
                                            "description": "An explanation about the purpose of this instance.",
                                            "type": "string"
                                        }
                                    }
                                }
                            },
                            "orderId": {
                                "description": "Unique identifier of the order.",
                                "type": "string"
                            }
                        }
                    },
                    "success": {
                        "description": "Condition if the request was successful.",
                        "type": "boolean"
                    }
                }
            }
        },
        "parameters": {
            "orderId": {
                "name": "orderId",
                "in": "path",
                "description": "Unique identifier of the order.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "1481050515517-01"
                }
            },
            "Content-Type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Type of the content being sent.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            },
            "Accept": {
                "name": "Accept",
                "in": "header",
                "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                "required": true,
                "style": "simple",
                "schema": {
                    "type": "string",
                    "example": "application/json"
                }
            }
        }
    },
    "tags": [
        {
            "name": "Order changes"
        },
        {
            "name": "Bin locations"
        }
    ]
}