{
    "openapi": "3.0.0",
    "info": {
        "title": "Promotions & Taxes API v2",
        "description": "\r\n> Check the new [Promotions onboarding guide](https://developers.vtex.com/vtex-rest-api/docs/promotions-overview). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Promotions and is organized by focusing on the developer's journey.\r\n\r\n The Promotions & Taxes API allows you to manage and retrieve all coupons from your VTEX store.",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://{accountName}.{environment}.com.br/api/rnb/v2/pvt",
            "description": "VTEX server URL",
            "variables": {
                "accountName": {
                    "description": "Name of the VTEX account. Used as part of the URL.",
                    "default": "apiexamples"
                },
                "environment": {
                    "description": "Environment to use. Used as part of the URL.",
                    "default": "vtexcommercestable"
                }
            }
        }
    ],
    "paths": {
        "/coupon": {
            "get": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Get coupons",
                "operationId": "Getgroupedcoupons",
                "description": "Retrieves the list of all active coupons.",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/getcoupons"
                                },
                                "example": {
                                    "items": [
                                        {
                                            "grouping": {
                                                "key": "rewardsprogram",
                                                "amount": 1000
                                            },
                                            "configuration": {
                                                "lastModifiedUtc": "2022-04-20T20:07:03.5066878Z",
                                                "utmSource": "fb",
                                                "utmCampaign": "rewards",
                                                "isArchived": false,
                                                "maxItemsPerClient": 0,
                                                "expirationIntervalPerUse": "00:00:00",
                                                "maxUsage": 3,
                                                "groupingKey": "rewardsprogram"
                                            }
                                        }
                                    ],
                                    "pagination": {
                                        "page": 0,
                                        "pageSize": 10,
                                        "total": 10
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/group/archived": {
            "get": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Get archived coupons",
                "operationId": "Getgroupedarchivedcoupons",
                "description": "Retrieves the list of all archived coupons.",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/getcoupons"
                                },
                                "example": {
                                    "items": [
                                        {
                                            "grouping": {
                                                "key": "rewardsprogram",
                                                "amount": 1000
                                            },
                                            "configuration": {
                                                "lastModifiedUtc": "2022-04-20T20:07:03.5066878Z",
                                                "utmSource": "fb",
                                                "utmCampaign": "rewards",
                                                "isArchived": true,
                                                "maxItemsPerClient": 0,
                                                "expirationIntervalPerUse": "00:00:00",
                                                "maxUsage": 3,
                                                "groupingKey": "rewardsprogram"
                                            }
                                        }
                                    ],
                                    "pagination": {
                                        "page": 0,
                                        "pageSize": 10,
                                        "total": 10
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/group/{groupingKey}": {
            "get": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Get coupon batch information",
                "description": "Retrieves information from a specific coupon batch based on its `groupingKey`.",
                "operationId": "Getcoupongroupinformation",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "groupingKey",
                        "in": "path",
                        "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "promo"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/getcoupongroupinfo"
                                },
                                "example": {
                                    "configuration": {
                                        "lastModifiedUtc": "2022-02-15T19:18:28.6409703Z",
                                        "utmSource": "fb",
                                        "utmCampaign": "rewards",
                                        "isArchived": false,
                                        "maxItemsPerClient": 13,
                                        "expirationIntervalPerUse": "00:00:00",
                                        "maxUsage": 11,
                                        "groupingKey": "12130984756"
                                    },
                                    "grouping": {
                                        "key": "12130984756",
                                        "amount": 5
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            },
            "put": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Edit coupon batch configuration",
                "description": "Changes information from a specific coupon batch configuration based on its `groupingKey`.",
                "operationId": "Editcoupongroupconfiguration",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "groupingKey",
                        "in": "path",
                        "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "promo"
                    }
                ],
                "requestBody": {
                    "description": "Request body to edit coupon batch configuration information.",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/editcoupongroupconfiguration"
                            },
                            "example": {
                                "utmSource": "source",
                                "isArchived": false,
                                "maxItemsPerClient": 0,
                                "expirationIntervalPerUse": "00:00:00",
                                "maxUsage": 4
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "title": "",
                                    "description": "Array of strings with coupon batch codes.",
                                    "items": {
                                        "type": "string",
                                        "title": "",
                                        "description": "Coupon code"
                                    },
                                    "example": [
                                        "12130984756-bbbsqz5lxivwvx7",
                                        "12130984756-31xj4idmfbmh9am",
                                        "12130984756-pxpdsou99n3bmsn",
                                        "12130984756-juzl9asvq8z4sjn",
                                        "12130984756-gyo7a2v0s9v7s07"
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "text/plain": {
                                "example": "It is not possible to edit an archived coupon group."
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/group/{groupingKey}/codes": {
            "get": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Get coupon batch codes",
                "description": "Retrieves a specific coupon batch's list of codes.",
                "operationId": "Getcoupongroupcodes.",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "groupingKey",
                        "in": "path",
                        "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "promo"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "title": "",
                                    "description": "Array of strings with coupon batch codes.",
                                    "items": {
                                        "type": "string",
                                        "title": "",
                                        "description": "Coupon code"
                                    },
                                    "example": [
                                        "12130984756-bbbsqz5lxivwvx7",
                                        "12130984756-31xj4idmfbmh9am",
                                        "12130984756-pxpdsou99n3bmsn",
                                        "12130984756-juzl9asvq8z4sjn",
                                        "12130984756-gyo7a2v0s9v7s07"
                                    ]
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "text/plain": {
                                "example": "Coupon Group Not Found"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/group/{groupingKey}/archive": {
            "put": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Archive a coupon batch",
                "description": "Archives a coupon batch and its respective codes.",
                "operationId": "Archivedcoupongroup",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "groupingKey",
                        "in": "path",
                        "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "promo"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "text/plain": {
                                "example": "Coupon Group Not Found"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/group": {
            "post": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Create coupon batches",
                "description": "Creates one or more coupon batches.",
                "operationId": "Creategroupsofcoupons",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/creategroupsofcouponsrequest"
                                },
                                "description": "Array of objects containing coupon batches information."
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "title": "",
                                        "description": "Coupon code"
                                    },
                                    "example": [
                                        "bf22-Y0RGX5VRCQU5HRQ",
                                        "bf22-XZC6SP9WYR1OINC",
                                        "bf22-DOLD2FF2NNHUGZU",
                                        "bf22-1E5WFBGOS2MAY9T",
                                        "bf22-CXK6H29W9K1PI2B"
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "text/plain": {
                                "example": "A list of multiple coupon configurations is required"
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/group/{groupingKey}/unarchive": {
            "put": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Unarchive a coupon batch",
                "description": "Unarchives a coupon batch and its respective codes.",
                "operationId": "Unarchivedcoupongroup",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "groupingKey",
                        "in": "path",
                        "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "promo"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/usage-count/{couponCode}": {
            "get": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Get usage count for a single coupon",
                "description": "Returns the number of times a specific single coupon was used, based on its `couponCode`.",
                "operationId": "Getnumberofusagesofasinglecoupon",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "couponCode",
                        "in": "path",
                        "description": "Single coupon code.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "blackfriday10"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "number",
                                    "title": "",
                                    "description": "Number of times the single coupon was used to place orders.",
                                    "example": 1
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/coupon/usage-count/group/{groupingKey}": {
            "get": {
                "tags": [
                    "Coupons"
                ],
                "summary": "Get usage count for a coupon batch",
                "description": "Returns the number of times a coupon batch was used, based on its `groupingKey`.",
                "operationId": "Getnumberofusagesofacouponbatch",
                "parameters": [
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "groupingKey",
                        "in": "path",
                        "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string"
                        },
                        "example": "rewardsprogram"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "number",
                                    "title": "",
                                    "description": "Number of times the coupon batch was used to place orders.",
                                    "example": 1
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        }
    },
    "components": {
        "schemas": {
            "creategroupsofcouponsrequest": {
                "title": "CreategroupsofcouponsRequest",
                "required": [
                    "couponConfiguration",
                    "quantity"
                ],
                "type": "object",
                "properties": {
                    "couponConfiguration": {
                        "$ref": "#/components/schemas/couponconfiguration"
                    },
                    "quantity": {
                        "type": "string"
                    }
                },
                "example": {
                    "couponConfiguration": {
                        "utmSource": "fb",
                        "utmCampaign": "blackfriday",
                        "couponCode": "bf22",
                        "expirationIntervalPerUse": "00:00:00",
                        "maxItemsPerClient": 5,
                        "maxUsage": 5
                    },
                    "quantity": "5"
                }
            },
            "couponconfiguration": {
                "title": "CouponConfiguration",
                "required": [
                    "couponCode",
                    "maxUsage"
                ],
                "type": "object",
                "properties": {
                    "utmSource": {
                        "title": "utmSource",
                        "description": "UTM source related to the coupon, which indicates the source of the traffic, that is, from which site, advertiser, or publication the user came from. It is mandatory to provide either `utmSource` or `utmCampaign`.",
                        "type": "string",
                        "example": "fb"
                    },
                    "utmCampaign": {
                        "title": "utmCampaign",
                        "description": "UTM campaign related to the coupon, which indicates the campaign that defines a particular marketing context. It is mandatory to provide either `utmSource` or `utmCampaign`.",
                        "type": "string",
                        "example": "blackfriday"
                    },
                    "couponCode": {
                        "title": "couponCode",
                        "description": "Coupon batch prefix.",
                        "type": "string",
                        "example": "rewards10"
                    },
                    "expirationIntervalPerUse": {
                        "title": "expirationIntervalPerUse",
                        "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of the Coupons module. When enabled, it determines how many days after purchase the coupon will be available for use again.",
                        "type": "string",
                        "example": "14.00:00:00"
                    },
                    "maxItemsPerClient": {
                        "title": "maxItemsPerClient",
                        "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of Coupons. When enabled, it determines the maximum amount of products to which the coupon can be applied. The defined quantity is valid for one or more purchases by the same customer.",
                        "type": "number",
                        "example": 0
                    },
                    "maxUsage": {
                        "title": "maxUsage",
                        "description": "The maximum number of times the coupon can be used, if the coupon has limited usage.",
                        "type": "number",
                        "example": 3
                    }
                },
                "example": {
                    "utmSource": "fb",
                    "utmCampaign": "blackfriday",
                    "couponCode": "bf22",
                    "expirationIntervalPerUse": "00:00:00",
                    "maxItemsPerClient": 5,
                    "maxUsage": 5
                }
            },
            "getcoupons": {
                "title": "",
                "description": "List of coupons.",
                "type": "object",
                "properties": {
                    "items": {
                        "title": "items",
                        "description": "Array of objects.",
                        "type": "array",
                        "items": {
                            "description": "Object containing each coupon batch and its configuration information.",
                            "type": "object",
                            "properties": {
                                "grouping": {
                                    "title": "grouping",
                                    "description": "Coupon batch.",
                                    "type": "object",
                                    "properties": {
                                        "key": {
                                            "title": "key",
                                            "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                                            "type": "string",
                                            "example": "rewardsprogram"
                                        },
                                        "amount": {
                                            "title": "amount",
                                            "description": "Amount of codes in the coupon batch.",
                                            "type": "number",
                                            "example": 1000
                                        }
                                    }
                                },
                                "configuration": {
                                    "title": "configuration",
                                    "description": "Object containing the coupon's properties.",
                                    "type": "object",
                                    "properties": {
                                        "lastModifiedUtc": {
                                            "title": "lastModifiedUtc",
                                            "description": "Date when the coupon was modified for the last time, in the UTC format.",
                                            "type": "string",
                                            "example": "2022-04-20T20:07:03.5066878Z"
                                        },
                                        "utmSource": {
                                            "title": "utmSource",
                                            "description": "UTM source related to the coupon, which indicates the source of the traffic, that is, from which site, advertiser, or publication the user came from.",
                                            "type": "string",
                                            "example": "fb"
                                        },
                                        "utmCampaign": {
                                            "title": "utmCampaign",
                                            "description": "UTM campaign related to the coupon, which indicates the campaign that defines a particular marketing context.",
                                            "type": "string",
                                            "example": "blackfriday"
                                        },
                                        "couponCode": {
                                            "title": "couponCode",
                                            "description": "Single coupon code.",
                                            "type": "string",
                                            "example": "welcome10"
                                        },
                                        "isArchived": {
                                            "title": "isArchived",
                                            "description": "Determines whether the coupon is archived (`true`) or not (`false`).",
                                            "type": "boolean",
                                            "example": false
                                        },
                                        "maxItemsPerClient": {
                                            "title": "maxItemsPerClient",
                                            "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of Coupons. When enabled, it determines the maximum amount of products to which the coupon can be applied. The defined quantity is valid for one or more purchases by the same customer.",
                                            "type": "number",
                                            "example": 0
                                        },
                                        "expirationIntervalPerUse": {
                                            "title": "expirationIntervalPerUse",
                                            "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of the Coupons module. When enabled, it determines how many days after purchase the coupon will be available for use again.",
                                            "type": "string",
                                            "example": "14.00:00:00"
                                        },
                                        "maxUsage": {
                                            "title": "maxUsage",
                                            "description": "The maximum number of times the coupon can be used, if the coupon has limited usage.",
                                            "type": "number",
                                            "example": 3
                                        },
                                        "groupingKey": {
                                            "title": "groupingKey",
                                            "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                                            "type": "string",
                                            "example": "rewardsprogram"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "pagination": {
                        "title": "pagination",
                        "description": "Pagination of the list of coupons.",
                        "type": "object",
                        "properties": {
                            "page": {
                                "title": "page",
                                "description": "Page number.",
                                "type": "integer",
                                "example": 0
                            },
                            "pageSize": {
                                "title": "pageSize",
                                "description": "Number of items per page.",
                                "type": "integer",
                                "example": 10
                            },
                            "total": {
                                "title": "total",
                                "description": "Total of pages.",
                                "type": "integer",
                                "example": 10
                            }
                        },
                        "example": {
                            "age": 0,
                            "pageSize": 10,
                            "total": 10
                        }
                    }
                }
            },
            "getcoupongroupinfo": {
                "title": "",
                "description": "Coupon batch information.",
                "type": "object",
                "properties": {
                    "configuration": {
                        "title": "configuration",
                        "description": "Object containing the coupon's properties.",
                        "type": "object",
                        "properties": {
                            "lastModifiedUtc": {
                                "title": "lastModifiedUtc",
                                "description": "Date when the coupon was modified for the last time, in the UTC format.",
                                "type": "string",
                                "example": "2022-04-20T20:07:03.5066878Z"
                            },
                            "utmSource": {
                                "title": "utmSource",
                                "description": "UTM source related to the coupon, which indicates the source of the traffic, that is, from which site, advertiser, or publication the user came from.",
                                "type": "string",
                                "example": "fb"
                            },
                            "utmCampaign": {
                                "title": "utmCampaign",
                                "description": "UTM campaign related to the coupon, which indicates the campaign that defines a particular marketing context.",
                                "type": "string",
                                "example": "blackfriday"
                            },
                            "isArchived": {
                                "title": "isArchived",
                                "description": "Determines whether the coupon is archived (`true`) or not (`false`).",
                                "type": "boolean",
                                "example": false
                            },
                            "maxItemsPerClient": {
                                "title": "maxItemsPerClient",
                                "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of Coupons. When enabled, it determines the maximum amount of products to which the coupon can be applied. The defined quantity is valid for one or more purchases by the same customer.",
                                "type": "number",
                                "example": 0
                            },
                            "expirationIntervalPerUse": {
                                "title": "expirationIntervalPerUse",
                                "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of the Coupons module. When enabled, it determines how many days after purchase the coupon will be available for use again.",
                                "type": "string",
                                "example": "14.00:00:00"
                            },
                            "maxUsage": {
                                "title": "maxUsage",
                                "description": "The maximum number of times the coupon can be used, if the coupon has limited usage.",
                                "type": "number",
                                "example": 3
                            },
                            "groupingKey": {
                                "title": "groupingKey",
                                "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                                "type": "string",
                                "example": "rewardsprogram"
                            }
                        }
                    },
                    "grouping": {
                        "title": "grouping",
                        "description": "Coupon batch.",
                        "type": "object",
                        "properties": {
                            "key": {
                                "title": "key",
                                "description": "Coupon grouping key, which is the prefix for the coupon batch's generated codes.",
                                "type": "string",
                                "example": "rewardsprogram"
                            },
                            "amount": {
                                "title": "amount",
                                "description": "Amount of codes in the coupon batch.",
                                "type": "number",
                                "example": 1000
                            }
                        }
                    }
                }
            },
            "editcoupongroupconfiguration": {
                "title": "Editcoupongroupconfiguration",
                "required": [
                    "isArchived",
                    "maxUsage"
                ],
                "type": "object",
                "properties": {
                    "utmSource": {
                        "title": "utmSource",
                        "description": "UTM source related to the coupon, which indicates the source of the traffic, that is, from which site, advertiser, or publication the user came from. It is mandatory to provide either `utmSource` or `utmCampaign`.",
                        "type": "string",
                        "example": "fb"
                    },
                    "utmCampaign": {
                        "title": "utmCampaign",
                        "description": "UTM campaign related to the coupon, which indicates the campaign that defines a particular marketing context. It is mandatory to provide either `utmSource` or `utmCampaign`.",
                        "type": "string",
                        "example": "blackfriday"
                    },
                    "isArchived": {
                        "title": "isArchived",
                        "description": "Determines whether the coupon is archived (`true`) or not (`false`).",
                        "type": "boolean",
                        "example": false
                    },
                    "maxItemsPerClient": {
                        "title": "maxItemsPerClient",
                        "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of Coupons. When enabled, it determines the maximum amount of products to which the coupon can be applied. The defined quantity is valid for one or more purchases by the same customer.",
                        "type": "number",
                        "example": 0
                    },
                    "expirationIntervalPerUse": {
                        "title": "expirationIntervalPerUse",
                        "description": "This option is non-editable and visible only for existing coupons configured with this limitation in previous versions of the Coupons module. When enabled, it determines how many days after purchase the coupon will be available for use again.",
                        "type": "string",
                        "example": "14.00:00:00"
                    },
                    "maxUsage": {
                        "title": "maxUsage",
                        "description": "The maximum number of times the coupon can be used, if the coupon has limited usage.",
                        "type": "number",
                        "example": 3
                    }
                },
                "example": {
                    "utmSource": "source",
                    "isArchived": false,
                    "maxItemsPerClient": 0,
                    "expirationIntervalPerUse": "00:00:00",
                    "maxUsage": 4
                }
            }
        }
    },
    "tags": [
        {
            "name": "Coupons"
        }
    ]
}